controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    lift_position_controller:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

lift_position_controller:
  ros__parameters:
    joints: [lift_joint]

joint_state_broadcaster:
  ros__parameters: {}
